import { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WikiRocket!",
  description: "Generated by create next app",
};

export default function Home() {
  return <main className={inter.className}></main>;
}
