import React from "react";
import type { Metadata } from "next";
import getAllUsers from "@/lib/getAllUsers";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Users Page",
  description: "Generated by create next app",
};

export default async function UsersPage() {

  // Please start getting the information about the users,
  // and when you're done, give me the information as an array of users."

  const userData: Promise<User[]> = getAllUsers();

  // While the program is getting the information, please wait until it's done.
  // When it's done, take the information it gave us and put it in a variable called 'users'

  const users = await userData;

  // Get some information from the program, and when it's ready, use it to do something


  const content = (
    <section className="flex min-h-screen flex-col  justify-between p-24">
      <h2 className="font-bold text-2xl">
        <Link href="/">Back to home</Link>
      </h2>
      <br />
      {users.map((user) => (
        <p key={user.id}>
          <Link href={`/users/${user.id}`}>{user.name}</Link>
        </p>
      ))}
    </section>
  );
  return content;
}
